[project]
name = "comfyui_ino_nodes"
description = "A collection of custom nodes for ComfyUI"
version = "1.0.1"
license = { file = "LICENSE" }
dependencies = ["inocloudreve", "inopyutils", "python-dotenv"]

[project.urls]
Repository = "https://github.com/nobandegani/comfyui_ino_nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "nobandegani"
DisplayName = "Ino Custom Nodes"
Icon = ""
